project:
  title: "monografia"
  output-dir: render/

author: ALBERSON DA SILVA MIRANDA
date: last-modified
date-format: "YYYY"

bibliography: [config/elementos/packages.bib, config/elementos/monografia.bib]
biblio-title: REFERÊNCIAS
link-citations: true
cite-method: biblatex

crossref:
  fig-prefix: Figura
  tbl-prefix: Tabela
  eq-prefix: Equação
  tbl-title: Tabela
  fig-title: Figura
  lof-title: LISTA DE FIGURAS
  lot-title: LISTA DE TABELAS

fig-cap-location: top

execute:
  echo: false
  cache: false
